language: node_js
node_js:
- 10.9.0
cache:
  yarn: true
  directories:
      - "node_modules"
jobs:
  include:
  - stage: Tests
    name: Unit Tests
    script: yarn unit-test
    name: Integration Tests
    script: yarn int-test
before_install:
- openssl aes-256-cbc -K $encrypted_a33c5b4e66cd_key -iv $encrypted_a33c5b4e66cd_iv
  -in config.json.enc -out config.json -d
